### ISSUE TITLE
Empty Sass @import folders result in error

### ISSUE THREAD

**Issue by illepic** [phase2/p2-theme-core#11]
If you attempt to import a folder (`@import "blah/blerp"`) and there are no `.scss` files within the folder, the following output results:

```
gulp-notify: [CSS Error - Line 31] scss/style.scss
Error: File to import not found or unreadable: ../source/_patterns/05-pages/**/*.scss
       Parent style sheet: /patternlab/scss/style.scss
        on line 31 of scss/style.scss
>> @import "../source/_patterns/05-pages/**/*.scss";
```

East solution is of course to ensure you're not @import'ing empty files. This can probably be tackled within css.js within p2-them-core libs tasks.

**Comment by EvanLovely** [comment]
That's totally on the dependency we're using, `gulp-sass-glob`; looks like the bug [was fixed](https://github.com/tomgrooffer/gulp-sass-glob/pull/22) already, but there's another issue where [people are asking him to go back to GitHub releases](https://github.com/tomgrooffer/gulp-sass-glob/issues/18) so they can know if that bug fix is rolled out yet or not. We're currently using his latest release, 1.0.8.
