### ISSUE TITLE
allow p2-theme-core to not reside in the parent directory

### ISSUE THREAD

**Issue by timcosgrove** [phase2/p2-theme-core#20]
css, js, and docs all use the del() package, e.g.:

https://github.com/phase2/p2-theme-core/blob/master/lib/css.js#L60

del() assumes that it resides in a parent directory of the files it is modifying. You can delete outside your piece of the directory tree with the 'force' opt:
https://www.npmjs.com/package/del#force

I would like the ability either to specify that I am forcing, or to have it turned on by default in p2-theme-core.

The use case is that p2-theme-core is not necessarily guaranteed to be installed at a root directory of the files it is modifying. For example, p2-theme-core might be included as part of a tools package that is distributed by Composer, which would put the package.json pulling it in at repo-root/vendor/my-tools/, but wanting to modify files that are elsewhere in repo-root/my-sweet-files.

**Comment by timcosgrove** [comment]
This might also extend beyond del(); that is just where I ran into it.

**Comment by EvanLovely** [comment]
Good call! Released in version 9.1.6
