### ISSUE TITLE
Sassdoc now reserves keyword 'verbose'

### ISSUE THREAD

**Issue by timcosgrove** [phase2/p2-theme-core#23]
With this change to sassdoc of 3 days prior: https://github.com/SassDoc/sassdoc/commit/c575fc5dea32aed590825531dc21d252573f92de

'verbose' is a reserved keyword and cannot be passed in. 

p2-theme-core calls sassdoc() w/ verbose here: https://github.com/phase2/p2-theme-core/blob/master/lib/css.js#L90

This breaks a css build.

**Comment by timcosgrove** [comment]
Opened https://github.com/SassDoc/sassdoc/issues/490

**Comment by illepic** [comment]
@timcosgrove: PR here for bumping sassdoc to `^2.2.2`, along with the package.lock file used by npm 5: https://github.com/phase2/p2-theme-core/pull/32

**Comment by timcosgrove** [comment]
Fixed w/ https://github.com/phase2/p2-theme-core/pull/32 . Thanks!
