### ISSUE TITLE
Convert from Sass to PostCSS

### ISSUE THREAD

**Issue by EvanLovely** [phase2/p2-theme-core#25]
There's already some PostCSS in but it's basically just used for AutoPrefixer. I think that CSSNext would be a good thing to use. Relates to https://github.com/phase2/pattern-lab-starter/issues/80

**Comment by webcultist** [comment]
Would it be possible to have this optional in this theme? I still see many advantages over using PostCSS as for example the very good editor implementations and as libSASS is very fast, I don't see the need to completely remove SASS. What do you think or what are the reasons you see the need to completely change all the SASS structures & workflows to postCSS?

**Comment by EvanLovely** [comment]
I always like the idea of using tools that let us use syntax that will one day be standard. So for example, we've got native CSS variables coming our way so let's start using them so we can get used to them as developers now. Additionally, this let's us use progressive enhancement; I'm sure that we can get it set up so that if a browser supports CSS vars natively it can use them and if not it uses the statically compiled values. This can let us do some really cool stuff. 

I see your bigger point though and that's letting people choose sub-sets of functionality to build up their own "theme core" - it's something I've wanted and thought about for a while now but still need to have a firm vision before it's possible to implement. I could see someone choosing a theme core and being asked if you wanted Sass or PostCSS. Again, there'd be a good chunk of work to break apart this repo into modular parts to allow that though. Let me think about it.

Also, since we need PostCSS to use Autoprefixer in the current state of the repo, it's possible that this could be a simple config option. Though then that means you'd need all the dependencies for both approaches installed, which makes it more bloated. The other thing I want to do in v10 is make this all smaller, so that goes against this.

**Comment by archnode** [comment]
One thing I implemented while working on something quite similar is something that could be used as an equivalent for scss2json for PostCSS. Maybe it's of use in this context: https://github.com/archnode/postcss-extract-variable-scheme. I use this by extracting files based on variable prefixes and process and move this files to their destination inside my patternlab structure.

**Comment by illepic** [comment]
Closing this as the p2-theme-core is going into feature freeze and v10 has been killed.
