### ISSUE TITLE
gulp-inject 4.3.2 modifies Twig files and leading to PL build failures.

### ISSUE THREAD

**Issue by timcosgrove** [phase2/p2-theme-core#42]
https://github.com/klei/gulp-inject 4.3.2 introduced Twig 'support': https://github.com/klei/gulp-inject/commit/831d4b0

This appears to process twig files with CSS and JS paths within them and wraps any file paths with `asset()`. I am unclear at which phase of a standard p2-theme-core `npm run compile` process this happens.

`asset()` is not a function that PatternLab appears to understand, at least at the version we are on (`pattern-lab/core v2.8.8`). Therefore the transform causes Pattern Lab to error out when it attempts to process twig files containing `asset()`.

Happy to provide any information necessary. We're on p2-theme-core 9.4.6. We fixed the problem locally by fixing on gulp-inject 4.3.1 in our own package.json, but this should get resolved if it's actually a p2-theme-core problem.

**Comment by markdboyd** [comment]
I opened #43 to pin `gulp-inject` to 4.3.1

**Comment by timcosgrove** [comment]
Fixed, ty!
