### ISSUE TITLE
Type error and Exit Status 1 at pl:full stage of compiling

### ISSUE THREAD

**Issue by fallenturtle** [phase2/p2-theme-core#6]
I apologize if this is better suited for the Pattern Lab Starter repo, but it seemed like the error was part of this repo. 
I recently upgraded to the newest node.js and NPM and when I run "npm run compile" it fails when it gets to pl:full. 
I'm not sure if its an issue with the scripts/library or more likely an issue with my environment. I've been attempting to use Homebrew and I'm working on a Mac running OS X 10.11.4 (El Capitan). After I was getting these errors I decided to install Gulp globally. I'm still getting these errors but if I do "Gulp compile" it works without issue.
I've attached the log file and also here's some of the output from command line from a few lines before pl:full up to the first "npm ERR!":

> [10:03:35] gulp-inject 7 files into footer.html.
> [10:03:35] gulp-inject 7 files into header.html.
> [10:03:35] Finished 'inject:pl' after 224 ms
> [10:03:35] Starting 'pl:full'...
> [10:03:36] 'pl:full' errored after 1.1 s
> [10:03:36] TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.extname (path.js:1429:5)
>     at /Users/abailey/Downloads/pattern-lab-starter-master 2/node_modules/patternlab-node/builder/media_hunter.js:24:13
>     at diveSync (/Users/abailey/Downloads/pattern-lab-starter-master 2/node_modules/diveSync/diveSync.js:62:5)
>     at findMediaQueries (/Users/abailey/Downloads/pattern-lab-starter-master 2/node_modules/patternlab-node/builder/media_hunter.js:23:4)
>     at Object.find_media_queries (/Users/abailey/Downloads/pattern-lab-starter-master 2/node_modules/patternlab-node/builder/media_hunter.js:45:5)
>     at buildFrontEnd (/Users/abailey/Downloads/pattern-lab-starter-master 2/node_modules/patternlab-node/builder/patternlab.js:178:18)
>     at Object.build (/Users/abailey/Downloads/pattern-lab-starter-master 2/node_modules/patternlab-node/builder/patternlab.js:463:7)
>     at Gulp.plBuild (/Users/abailey/Downloads/pattern-lab-starter-master 2/node_modules/p2-theme-core/lib/pattern-lab.js:16:56)
>     at module.exports (/Users/abailey/Downloads/pattern-lab-starter-master 2/node_modules/orchestrator/lib/runTask.js:34:7)

[abailey_pl_16-05-07-npm-debug.txt](https://github.com/phase2/p2-theme-core/files/253451/abailey_pl_16-05-07-npm-debug.txt)

**Comment by EvanLovely** [comment]
Could you try opening `package.json` and removing the `precompile` and `prestart` scripts that run `npm run checkDeps`?

**Comment by fallenturtle** [comment]
I tried as you suggested but I'm still seeing the same errors.

**Comment by EvanLovely** [comment]
Still having these issues even with the latest? And yes, I think this is an issue with phase2/pattern-lab-starter and not this one. Let us know if you have it working!

**Comment by drupalshift** [comment]
This problem is from `path.js` in `Node v6.*` , I'm struggling with this issue too , let me know if you solve it , i will also post if i can make it work

**Comment by EvanLovely** [comment]
Hmmm... I think that may be a pattern-lab/patternlab-node issue when I look closer at the error dump. Could it be the space you have in your path name? (`Downloads/pattern-lab-starter-master 2/`). Also, I dropped support for Pattern Lab node in the current major version of this repo and we are using PHP Pattern Lab 2 with the Twig engine now. You could set `config.patternLab.enable` to false and then use these tools for all the other things they done and then add your own watch and compile tasks to your `gulpfile.js` to get the two working together. Good luck!
